# Generated by Django 5.2.7 on 2025-10-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_up',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_up',
        ),
    ]
